### ISSUE TITLE
Cannot use in vite/2.7.1

### ISSUE THREAD

**Issue by TJKoury** [mathe42/vite-plugin-worker#13]
Attempts import as a CommonJS file, forcing use of `dist/index.mjs` results in failed imports (`pluginHelper is not a function`)

vite/2.7.1 linux-x64 node-v14.15.5

**Comment by mathe42** [comment]
Can you provide a full reproduction?

**Comment by mathe42** [comment]
Closing this as no reproduction was provided. If the issue still exists please open a new issue with a reproduction!
