### ISSUE TITLE
use `new Worker(new URL(path, import.meta.url), {type: "module"})`

### ISSUE THREAD

**Issue by zxch3n** [mathe42/vite-plugin-worker#16]
Using this format can enable Deno to import workers correctly from vite dev server.

https://github.com/mathe42/vite-plugin-worker/blob/a788c1a5cb3a525a26c2de66013d3c2ea927f15b/src/worker/worker.ts#L50-L57

**Comment by mathe42** [comment]
Can you provide a full example? I don't fully understand why you want to import Code (Frontend) in deno (Backend)

**Comment by zxch3n** [comment]
Deno can be used to run tests without launching a real browser. 

Example https://github.com/zxch3n/ts-rust-parallel-template

**Comment by mathe42** [comment]
LGTM. Does this work with workers in workers? That is the only thing I'm not shure about...

**Comment by zxch3n** [comment]
I found that there is something wrong with this approach.

**Comment by zxch3n** [comment]
It turns out Deno works fine already with the current version of vite-plugin-worker. It was my config that caused the error.
