### ISSUE TITLE
"bundleHelper" is not a function

### ISSUE THREAD

**Issue by moomoolive** [mathe42/vite-plugin-worker#19]
Hey guys,

I tried using this awesome package today, but every time I attempt to import the "bundleHelper" function it returns undefined.

from console:
![image](https://user-images.githubusercontent.com/63522515/149569258-b06fca38-719a-459b-8d44-a986ca6207c1.png)

VsCode error:
![image](https://user-images.githubusercontent.com/63522515/149569309-07b8c00d-c43c-4e05-812d-e8d648aabca1.png)

I attempted to re-install package multiple times (with and without reinstalling node_modules), but still no luck.

Not sure if it's only my machine, but here are the dependencies I'm using:

Vite: 2.5.1
Node: 16.13.1
NPM: 8.1.2
vite-plugin-worker: 1.0.5
OS: ubuntu-20.04

PS Thanks for the amazing work on this package, the API is quite nice

**Comment by moomoolive** [comment]
Nevermind solved the issue, import is now called "pluginHelper"

**Comment by carlobeltrame** [comment]
This should be changed in the README then, no?

**Comment by mathe42** [comment]
Yes sorry - is changed!

**Comment by moomoolive** [comment]
Sorry guys, I probably should have created a PR to update Readme... But I was lazy😅. Appreciate the response
